# Numpy基础： 数组与向量化计算
## Numpy内容：
1. ndarray ，一种高效多维数组，提供了便捷灵活的API。
2. 对所有数据进行快速的矩阵计算
3. 数组IO
4. 线性代数，随机数生成，傅里叶变换

### 我们所关注的内容：
1. 数据处理，清洗，过滤，变换，计算
2. 常见数组操作sort,unique,set

## Numpy ndarray:多维数组对象

In [3]:
import numpy as np

# 生成随机数组
data = np.random.randn(2,3)

data

array([[-0.00411722,  0.82729381,  1.74359454],
       [ 0.3076142 ,  1.30566986, -1.57590026]])

In [4]:
# 数学操作
data * 10

array([[ -0.04117223,   8.27293813,  17.43594538],
       [  3.07614196,  13.05669857, -15.75900265]])

In [5]:
data + data

array([[-0.00823445,  1.65458763,  3.48718908],
       [ 0.61522839,  2.61133971, -3.15180053]])

一个ndarray是一个通用的多维同列数据容器。每一个数组都有一个shape属性，用来表征数组维度。没有给数组都有dtype属性，用来描述
数组的数据类型

In [9]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

生成ndarray 最简单的方式就是array函数。
array函数可以接受任意的序列型对象。

In [10]:
# data 1是一个list
data1 = [6,7.5,8,0,1]

In [11]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

除非显示指定，否则np.array会自动推断生成数组的数据类型，数据类型被存储在dtype中

In [15]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


除了np.array，还有很多其他函数可以创建新数组。例如zeros可以一次性创造全0数组，ones可以一次性创造全1数组。empty可以创建一个没有初始化数值的数值。
如果没有特别指明，默认的数组类型float 64

## 数组生成函数：
array
asarray 将输入转换为ndarray
arange python自带的range的nnumpy版本，返回一个数组
ones 根据给定形状和数据类型生成全1数组
ones_like 根据所给的数组生成一个形状一样的全0数组